id: PAADFA671
initial_creation_type: input
source_metadata:
  title: Magnetizing Series
  language: en
  description: 'Texts on the theme of magnetizing or bringing under one’s control
    (dbang du sdud pa):'
  volume:
    9a2c3689cbdc415ab42a5b85d96f2315:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    08c42525f0224a8baf710d5ce6480c76:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    8edab289d7894663aa96ec9a31d76245:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Sādhanas
created_at: '2022-03-01T04:30:45.114354'
last_modified_at: '2022-03-01T04:30:45.114361'
